### ISSUE TITLE
Feature: New term

### ISSUE THREAD

**Issue by pjxiao** [pjxiao/redmine_glossary#15]
# Purpose

* Implement the feature let us create a term

# TODOs

* [x] Examine functions of this feature
* [x] Add or modify the baseline implementation
* [x] Fixup the templates
* [x] Add tests

# Spec

* TODO: _New term_ do something...

# Reference implementations

* https://github.com/redmine/redmine/blob/7afb5b7f/app/views/issues/_list.html.erb#L8
* https://github.com/redmine/redmine/blob/7afb5b7f/app/views/issues/index.html.erb#L1

# References and hints

* https://github.com/redmine/redmine/commit/46b04f3a#diff-3e5e9f6f685bf848f0a777187ab65e53
* https://guides.rubyonrails.org/testing.html#implementing-an-integration-test
