### ISSUE TITLE
Feature: New category popup

### ISSUE THREAD

**Issue by pjxiao** [pjxiao/redmine_glossary#16]
# Purpose

* Implement the feature let us create a term category while we're creating/editing a term

# TODOs

* [ ] Examine functions of this feature
* [ ] Add or modify the baseline implementation
* [ ] Fixup the templates
* [ ] Add tests

# Spec

* TODO: _New category popup_ do something...

# Reference implementations

* TODO

# References and hints

* TODO
